services:
  - type: web
    name: lamini-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn api:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    region: oregon